name: Publish .NET app to Ubuntu self-hosted runner

on:
  push:
    branches: 
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  get-current-date:
    runs-on: self-hosted
    outputs:
      RELEASE_DATE: ${{ steps.get-date.outputs.RELEASE_DATE }}
    steps:
      - name: Get current date
        id: get-date
        run: echo "RELEASE_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

  restore:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Restore dependencies
        run: dotnet restore
    
  build:
    runs-on: self-hosted
    needs: restore
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build application
        run: dotnet build --configuration Release
  
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run tests
        run: dotnet test

  publish:
    runs-on: self-hosted
    needs:
      - get-current-date
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Publish application
        run: dotnet publish -c Release --runtime linux-x64 --self-contained true --output ./publish/release-${{ needs.get-current-date.outputs.RELEASE_DATE }}
  
