CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "MealPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_MealPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "Recipes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedDate" timestamp with time zone NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Recipes" PRIMARY KEY ("Id")
);

CREATE TABLE "Meals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MealDate" timestamp with time zone NOT NULL,
    "RecipeId" integer NOT NULL,
    "MealName" text NOT NULL,
    "MealPlanId" integer,
    CONSTRAINT "PK_Meals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Meals_MealPlans_MealPlanId" FOREIGN KEY ("MealPlanId") REFERENCES "MealPlans" ("Id"),
    CONSTRAINT "FK_Meals_Recipes_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Meals_MealPlanId" ON "Meals" ("MealPlanId");

CREATE INDEX "IX_Meals_RecipeId" ON "Meals" ("RecipeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250722121905_InitialCreate', '9.0.0');

COMMIT;

