# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish .NET app to Ubuntu self-hosted runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clean publish folder
      run: rm -rf ./publish
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --runtime linux-x64 --self-contained true --output ./publish
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run Ansible web playbook
      uses: dawidd6/action-ansible-playbook@v4
      with:
        playbook: /home/ubuntu/gitrepos/homelab/ansible/playbooks/setup_web.yaml
        options: --inventory /home/ubuntu/gitrepos/homelab/ansible/inventory/prod/inventory.yaml